const express = require("express");
const errorHandler = require("../middleware/error");
const authRouter = require("./authRouter");
const cartRouter = require("./cartRouter");
const checkoutRouter = require("./checkoutRouter");
const courseRouter = require("./courseRouter");
const publicRouter = require("./publicRouter");
const userRouter = require("./useRouter");
const router = express.Router();
router.use("/pub", publicRouter);
router.use("/courses", courseRouter);
router.use("/", authRouter);
router.use("/", checkoutRouter);
router.use("/users", userRouter);
router.use("/carts", cartRouter);
router.use(errorHandler);
module.exports = router;
